version: 2
jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build ssh image
          command: docker-compose build
      - run:
          name: Run terraform init
          command: docker-compose run ssh terraform init
      - run:
          name: Run terraform plan
          command: docker-compose run ssh terraform plan -out=./output.tfplan
      - run:
          name: Run terraform apply
          command: docker-compose run ssh terraform apply output.tfplan -auto-approve
      - run:
          name: Clear garbage
          command: rm output.tfplan
workflows:
  version: 2
  deploy:
    jobs:
      - deploy
